url: https://thecommittee.me

# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Yang Chen
  pic: Yang
  position: Baritone
  knownfor: #dammitYang

- name: Ethan Brady
  pic: Ethan
  position: Bass
  
- name: Sahaana Raveetharan
  pic: Sahaana
  position: Soprano
  
- name: Rishi Narale
  pic: Rishi
  position: Vocal Percussion / Bass
  
- name: Lishni Salgado
  pic: Lishni
  position: Soprano
  
- name: Leeann Lu
  pic: Leeann
  position: Soprano / Alto
  
- name: Trong
  pic: Trong
  position: Tenor / Baritone
  
- name: Manuel (Manny) Arab
  pic: Manny
  position: Tenor / Baritone / Vocal Percussion
  
- name: Kokulamenon (Koby) Pathmanathar
  pic: Koby
  position: Tenor
  
- name: Khoa Tran
  pic: Khoa
  position: Tenor

- name: Elia Lam
  pic: Elia
  position: Alto
  
- name: Mickey dyke
  pic: Mickey
  position: Alto
  
- name: Kenique Toppin
  pic: Kenique
  position: Alto

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty